import { JobCategory, UserRole } from '@/db/schema';

export const mockJobs = [
  {
    id: 1,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.IT,
    location: 'Remote',
    wage: 12000,
    image: 'https://via.placeholder.com/150',
    userId: 1,
  },
  {
    id: 2,
    title: 'Moving truck driver',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.LOGISTIC,
    location: 'Seichuan',
    wage: 3000,
    image: 'https://via.placeholder.com/150',
    userId: 1,
  },
  {
    id: 3,
    title: 'Nurse',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.HEALTHCARE,
    location: 'Guangxi',
    wage: 8000,
    image: 'https://via.placeholder.com/150',
    userId: 2,
  },
  {
    id: 4,
    title: 'High School Teacher',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.EDUCATION,
    location: 'Beijing',
    wage: 3000,
    image: 'https://via.placeholder.com/150',
    userId: 2,
  },
  {
    id: 5,
    title: 'Gardener',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.OCCUPATIONS,
    location: 'Hong Kong',
    wage: 2000,
    image: 'https://via.placeholder.com/150',
    userId: 3,
  },
  {
    id: 6,
    title: 'Private detective',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.OTHERS,
    location: 'Taipei',
    wage: 2000,
    image: 'https://via.placeholder.com/150',
    userId: 3,
  },
  {
    id: 7,
    title: 'Salesperson',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.SALES,
    location: 'Manila',
    wage: 4000,
    image: 'https://via.placeholder.com/150',
    userId: 4,
  },
  {
    id: 8,
    title: 'Tourism guide',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.TOURISM,
    location: 'Seoul',
    wage: 8000,
    image: 'https://via.placeholder.com/150',
    userId: 4,
  },
  {
    id: 9,
    title: 'Pharmacist',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.HEALTHCARE,
    location: 'Busan',
    wage: 9000,
    image: 'https://via.placeholder.com/150',
    userId: 5,
  },
  {
    id: 10,
    title: 'IT Support',
    description: 'Lorem ipsum dolor sit amet',
    category: JobCategory.IT,
    location: 'Remote',
    wage: 14000,
    image: 'https://via.placeholder.com/150',
    userId: 5,
  },
];

export const mockUsers = [
  {
    id: 1,
    email: 'JnJt3@gmail.com',
    isActive: true,
    name: 'John Doe',
    password: 'john12doe',
    role: UserRole.ADMIN,
  },
  {
    id: 2,
    email: 'O6ds9d@gmail.com',
    isActive: true,
    name: 'Harold Doe',
    password: 'harold12doe',
    role: UserRole.USER,
  },
  {
    id: 3,
    email: 'IOid2@gmail.com',
    isActive: true,
    name: 'Mike Smith',
    password: 'mike12smith',
    role: UserRole.USER,
  },
  {
    id: 4,
    email: 'IO2kl@gmail.com',
    isActive: true,
    name: 'Steve Jobs',
    password: 'job12steve',
    role: UserRole.USER,
  },
  {
    id: 5,
    email: 'O6ds9d@gmail.com',
    isActive: true,
    name: 'Ryan Air',
    password: 'ryan12air',
    role: UserRole.USER,
  },
];
