export const mockJobs = [
  {
    id: 1,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 6,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 7,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 8,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 9,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 10,
    title: 'Software Engineer',
    description: 'Lorem ipsum dolor sit amet',
    category: 'Engineering',
    location: 'Remote',
    wage: 10000,
    image: 'https://via.placeholder.com/150',
  },
];
